name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

env:
  NAME: 'github-actions[bot]'
  EMAIL: 'github-actions[bot]@users.noreply.github.com'
  INPUT: jupyter
  OUTPUT: databricks

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependenciers
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python bryckster.py run --input_path $INPUT --output_path $OUTPUT
        rm jupyter/*.ipynb
        echo "Please check Databricks notebook output in $OUTPUT" > jupyter/output.ok
    - name: Commit
      run: |
        git config --global user.email "$EMAIL"
        git config --global user.name "$NAME"
        git add jupyter
        git add databricks
        git commit -m "Convert to Databricks"
        git push origin main