name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependenciers
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python bryckster.py run --input_path jupyter --output_path databricks
        rm jupyter/*.ipynb